FROM python:3.10-slim

WORKDIR /app

# Copy your whole project (or just what's needed for Streamlit)
COPY . .

# Install dependencies
RUN pip install --upgrade pip
RUN pip install --no-cache-dir -r api/requirements.txt

# Expose Streamlit's default port
EXPOSE 8501

# Set Streamlit entrypoint
CMD ["streamlit", "run", "app/app.py", "--server.port=8501", "--server.enableCORS=false"]