CREATE TABLE IF NOT EXISTS housing_data (
  id INT AUTO_INCREMENT PRIMARY KEY,
  price FLOAT,
  n_rooms VARCHAR(50),
  area VARCHAR(100),
  build_year FLOAT,
  price_per_sqft FLOAT,
  size_sqft INT,
  street VARCHAR(255),
  n_bedrooms INT,
  n_bathrooms INT,
  district VARCHAR(255),
  region VARCHAR(100),
  scraped_date DATE,
  flat_age FLOAT,
  lease_remaining FLOAT,
  price_per_bedroom FLOAT,
  size_per_room FLOAT,
  bed_bath_ratio FLOAT,
  scraped_month INT,
  scraped_year INT,
  is_central TINYINT,
  is_mature_town TINYINT,
  age_size_interaction FLOAT,
  lease_price_interaction FLOAT,
  block VARCHAR(50)
);
